/**
 * Generate a language-aware format-on-edit PostToolUse hook.
 * Returns JS source as a string. Pure: no IO.
 *
 * The generated code uses string concatenation, not template literals,
 * so embedding it inside this module's template literal needs no escaping.
 *
 * @module generate/format-hook
 */

/** @typedef {import('../profile.mjs').ProjectProfile} ProjectProfile */

/**
 * @param {ProjectProfile} profile
 * @returns {string}
 */
export function renderFormatOnEdit(profile) {
  const names = new Set((profile.languages || []).map((l) => l.name));

  const hasJsLike = names.has("JavaScript") || names.has("TypeScript") ||
    names.has("Vue") || names.has("Svelte") || names.has("Astro");
  const hasPHP   = names.has("PHP");
  const hasPython = names.has("Python");
  const hasGo    = names.has("Go");
  const hasRust  = names.has("Rust");
  const hasRuby  = names.has("Ruby");
  const hasDart  = names.has("Dart");
  const hasCC    = names.has("C") || names.has("C++");

  // No languages detected → include JS/TS as safe default.
  const forceJsLike = !hasJsLike && !hasPHP && !hasPython && !hasGo &&
    !hasRust && !hasRuby && !hasDart && !hasCC;

  /** @type {{ condition: string, body: string }[]} */
  const blocks = [];

  if (hasJsLike || forceJsLike) blocks.push(JS_BLOCK);
  if (hasPHP)    blocks.push(PHP_BLOCK);
  if (hasPython) blocks.push(PYTHON_BLOCK);
  if (hasGo)     blocks.push(GO_BLOCK);
  if (hasRust)   blocks.push(RUST_BLOCK);
  if (hasRuby)   blocks.push(RUBY_BLOCK);
  if (hasDart)   blocks.push(DART_BLOCK);
  if (hasCC)     blocks.push(CC_BLOCK);

  return buildHook(blocks);
}

/**
 * @param {{ condition: string, body: string }[]} blocks
 * @returns {string}
 */
function buildHook(blocks) {
  const chain = blocks
    .map((b, i) => (i === 0 ? "if" : "else if") + " (" + b.condition + ") {\n" + b.body + "\n  }")
    .join(" ");

  return "#!/usr/bin/env node\n" +
    "/**\n" +
    " * PostToolUse hook: format the file Claude just edited.\n" +
    " * Generated by aia-harness — language-aware. Never blocks.\n" +
    " */\n" +
    "import fs from \"node:fs\";\n" +
    "import path from \"node:path\";\n" +
    "import { execFileSync } from \"node:child_process\";\n" +
    "\n" +
    "function readStdin() {\n" +
    "  try { return fs.readFileSync(0, \"utf8\"); } catch { return \"\"; }\n" +
    "}\n" +
    "\n" +
    "let event = {};\n" +
    "try { event = JSON.parse(readStdin() || \"{}\"); } catch { process.exit(0); }\n" +
    "\n" +
    "const file = event && event.tool_input && (event.tool_input.file_path || event.tool_input.path);\n" +
    "if (!file || typeof file !== \"string\") process.exit(0);\n" +
    "\n" +
    "const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd();\n" +
    "const ext = path.extname(file).toLowerCase();\n" +
    "\n" +
    "function localBin(name) {\n" +
    "  var p = path.join(projectDir, \"node_modules\", \".bin\", name);\n" +
    "  return fs.existsSync(p) ? p : null;\n" +
    "}\n" +
    "\n" +
    "try {\n" +
    "  " + chain + "\n" +
    "} catch {\n" +
    "  // Formatting is best-effort; never block the edit.\n" +
    "}\n" +
    "\n" +
    "process.exit(0);\n";
}

/** @type {{ condition: string, body: string }} */
const JS_BLOCK = {
  condition: "[\".js\",\".jsx\",\".ts\",\".tsx\",\".mjs\",\".cjs\",\".mts\",\".cts\"," +
    "\".json\",\".jsonc\",\".css\",\".scss\",\".sass\",\".less\"," +
    "\".md\",\".mdx\",\".html\",\".htm\",\".yaml\",\".yml\"," +
    "\".vue\",\".svelte\",\".astro\"].includes(ext)",
  body: "    var biome = localBin(\"biome\");\n" +
    "    var prettier = localBin(\"prettier\");\n" +
    "    if (biome) execFileSync(biome, [\"format\", \"--write\", file], { stdio: \"ignore\" });\n" +
    "    else if (prettier) execFileSync(prettier, [\"--write\", file], { stdio: \"ignore\" });",
};

/** @type {{ condition: string, body: string }} */
const PHP_BLOCK = {
  condition: "[\".php\",\".phtml\"].includes(ext)",
  body: "    var pint = path.join(projectDir, \"vendor\", \"bin\", \"pint\");\n" +
    "    if (fs.existsSync(pint)) execFileSync(pint, [file], { stdio: \"ignore\" });",
};

/** @type {{ condition: string, body: string }} */
const PYTHON_BLOCK = {
  condition: "[\".py\",\".pyi\"].includes(ext)",
  body: "    var venvDir = process.platform === \"win32\" ? \"Scripts\" : \"bin\";\n" +
    "    var venvBin = path.join(projectDir, \".venv\", venvDir);\n" +
    "    var ruffExe = process.platform === \"win32\" ? \"ruff.exe\" : \"ruff\";\n" +
    "    var blackExe = process.platform === \"win32\" ? \"black.exe\" : \"black\";\n" +
    "    var ruff = fs.existsSync(path.join(venvBin, ruffExe)) ? path.join(venvBin, ruffExe) : \"ruff\";\n" +
    "    var black = fs.existsSync(path.join(venvBin, blackExe)) ? path.join(venvBin, blackExe) : \"black\";\n" +
    "    try { execFileSync(ruff, [\"format\", \"--quiet\", file], { stdio: \"ignore\" }); }\n" +
    "    catch { try { execFileSync(black, [\"--quiet\", file], { stdio: \"ignore\" }); } catch { /* none */ } }",
};

/** @type {{ condition: string, body: string }} */
const GO_BLOCK = {
  condition: "ext === \".go\"",
  body: "    execFileSync(\"gofmt\", [\"-w\", file], { stdio: \"ignore\" });",
};

/** @type {{ condition: string, body: string }} */
const RUST_BLOCK = {
  condition: "ext === \".rs\"",
  body: "    execFileSync(\"rustfmt\", [file], { stdio: \"ignore\" });",
};

/** @type {{ condition: string, body: string }} */
const RUBY_BLOCK = {
  condition: "[\".rb\",\".erb\"].includes(ext)",
  body: "    try {\n" +
    "      execFileSync(\"bundle\", [\"exec\", \"rubocop\", \"--autocorrect-all\", \"--no-server\", file],\n" +
    "        { cwd: projectDir, stdio: \"ignore\" });\n" +
    "    } catch {\n" +
    "      execFileSync(\"rubocop\", [\"--autocorrect-all\", \"--no-server\", file], { stdio: \"ignore\" });\n" +
    "    }",
};

/** @type {{ condition: string, body: string }} */
const DART_BLOCK = {
  condition: "ext === \".dart\"",
  body: "    execFileSync(\"dart\", [\"format\", file], { stdio: \"ignore\" });",
};

/** @type {{ condition: string, body: string }} */
const CC_BLOCK = {
  condition: "[\".c\",\".h\",\".cc\",\".cpp\",\".cxx\",\".hpp\"].includes(ext)",
  body: "    var hasConfig = [\".clang-format\",\"_clang-format\"].some(\n" +
    "      function(f) { return fs.existsSync(path.join(projectDir, f)); });\n" +
    "    if (hasConfig) execFileSync(\"clang-format\", [\"-i\", file], { stdio: \"ignore\" });",
};
