/**
 * Miscellaneous generated artifacts: strategy doc, .lsp.json, worktree config,
 * and the market install script.
 *
 * @module generate/misc
 */
import { commandsBlock } from "./claude-md.mjs";
import { marketplaceRepo } from "../data/plugins-catalog.mjs";

/** @typedef {import('../profile.mjs').ProjectProfile} ProjectProfile */

/** Map a primary language to a Language Server config. */
const LSP_SERVERS = {
  TypeScript: { command: "npx", args: ["-y", "typescript-language-server", "--stdio"] },
  JavaScript: { command: "npx", args: ["-y", "typescript-language-server", "--stdio"] },
  PHP: { command: "npx", args: ["-y", "intelephense", "--stdio"] },
  Python: { command: "npx", args: ["-y", "pyright-langserver", "--stdio"] },
  Go: { command: "gopls", args: [] },
  Rust: { command: "rust-analyzer", args: [] },
};

/**
 * @param {ProjectProfile} profile
 * @returns {string}
 */
export function renderStrategies(profile) {
  const c = profile.commands;
  const lang = profile.primaryLanguage ?? "unknown";
  return `# Harness strategies

Generated by aia-harness for a **${lang}** project (commands source: ${c.source}).

## Lint & format
${[c.lint && `- Lint: \`${c.lint}\``, c.format && `- Format: \`${c.format}\``].filter(Boolean).join("\n") || "- No linter detected. Consider adding one."}

## Compilation / typecheck
${c.typecheck ? `- \`${c.typecheck}\`` : "- No typecheck step detected."}

## Language server
${
  LSP_SERVERS[/** @type {keyof typeof LSP_SERVERS} */ (lang)]
    ? `- Suggested LSP: \`${LSP_SERVERS[/** @type {keyof typeof LSP_SERVERS} */ (lang)].command} ${LSP_SERVERS[/** @type {keyof typeof LSP_SERVERS} */ (lang)].args.join(" ")}\` (see \`.lsp.json\`).`
    : "- No standard language server mapping for this stack."
}

## Unit testing
${c.test ? `- \`${c.test}\`` : "- No test runner detected. Add one and wire it into CI."}

## Canonical command reference
${commandsBlock(c)}
`;
}

/**
 * @param {ProjectProfile} profile
 * @returns {string|null}
 */
export function renderLspJson(profile) {
  const lang = /** @type {keyof typeof LSP_SERVERS} */ (profile.primaryLanguage ?? "");
  const server = LSP_SERVERS[lang];
  if (!server) return null;
  const key = lang === "JavaScript" || lang === "TypeScript" ? "typescript" : lang.toLowerCase();
  return JSON.stringify({ lspServers: { [key]: { type: "stdio", ...server } } }, null, 2) + "\n";
}

/**
 * @returns {string}
 */
export function renderWorktreeInclude() {
  return `# Files copied into every new worktree (aia-harness)
.claude/settings.local.json
.env
.env.local
`;
}

/**
 * Build the project-level tools section of the install script.
 * @param {import('../data/tools-catalog.mjs').ToolDef[]} tools
 * @returns {string}
 */
export function renderToolsInstallSection(tools) {
  const ids = new Set(tools.map((t) => t.id));
  /** @type {string[]} */
  const lines = [];
  const vendored = tools.filter((t) => t.strategy === "vendor").map((t) => t.id);
  if (vendored.length > 0) {
    lines.push(`#   vendored into .claude/ (no machine install needed): ${vendored.join(", ")}`);
  }
  if (ids.has("rtk")) {
    lines.push("#   rtk (token proxy) — PreToolUse hook already wired (guarded). Install the binary:");
    lines.push("#     brew install rtk   # or: curl -fsSL https://raw.githubusercontent.com/rtk-ai/rtk/refs/heads/master/install.sh | sh");
  }
  if (ids.has("graphify")) {
    lines.push("#   graphify (code graph) — project-level:");
    lines.push("#     uv tool install graphifyy");
    lines.push("#     graphify install --project && graphify claude install && graphify hook install");
    lines.push("#     graphify .   # build the graph, then: git add graphify-out/");
  }
  return lines.length > 0 ? lines.join("\n") : "#   (none)";
}

/**
 * A runnable installer for the suggested plugins (like plugin-dev's
 * dev-plugins-install.sh). Idempotent; prompts unless run with `-y`.
 * NOTE: Claude Code installs plugins at USER level — there is no per-project
 * plugin install — so this is the one step that is not project-scoped.
 * @param {import('../data/plugins-catalog.mjs').PluginSuggestion[]} plugins
 * @returns {string}
 */
export function renderPluginsInstallScript(plugins) {
  const names = [...new Set(plugins.map((p) => p.marketplace))];
  const mpAdds = names.map((n) => `claude plugin marketplace add ${marketplaceRepo(n)} || true`).join("\n");
  const installs = plugins.map((p) => `claude plugin install ${p.name}@${p.marketplace} || true`).join("\n");
  const listing = plugins.map((p) => `  - ${p.name} [${p.purpose}] ${p.description}`).join("\n");

  return `#!/usr/bin/env bash
# Generated by aia-harness — install the suggested Claude Code plugins.
# Plugins install at USER level (Claude Code has no per-project plugin install).
# Run with -y to skip the confirmation prompt.
set -euo pipefail

if ! command -v claude >/dev/null 2>&1; then
  echo "aia-harness: 'claude' CLI not found — install Claude Code first." >&2
  exit 1
fi

if [ "\${1:-}" != "-y" ]; then
  echo "About to add ${names.length} marketplace(s) and install ${plugins.length} plugin(s):"
  cat <<'PLUGINS'
${listing}
PLUGINS
  printf "Proceed? [y/N] "
  read -r ANS
  case "$ANS" in
    y | Y) ;;
    *) echo "Aborted."; exit 0 ;;
  esac
fi

# Marketplaces
${mpAdds}

# Plugins
${installs}

echo "Done. Restart Claude Code to load the new plugins."
`;
}

/**
 * @param {ProjectProfile} profile
 * @returns {string}
 */
export function renderGraphifyignore(profile) {
  const base = [
    "# .graphifyignore — gitignore syntax, merged with .gitignore (! negations win last).",
    "node_modules/",
    "dist/",
    "build/",
    "out/",
    "coverage/",
    ".next/",
    ".nuxt/",
    ".turbo/",
    "*.min.js",
    "*.generated.*",
  ];
  /** @type {string[]} */
  const extra = [];
  switch (profile.primaryLanguage) {
    case "Rust":
      extra.push("target/");
      break;
    case "Java":
    case "Kotlin":
      extra.push("target/", ".gradle/");
      break;
    case "PHP":
      extra.push("vendor/");
      break;
    case "Go":
      extra.push("vendor/", "bin/");
      break;
    case "Python":
      extra.push("__pycache__/", ".venv/", "venv/", ".mypy_cache/");
      break;
    default:
      break;
  }
  return [...base, ...extra].join("\n") + "\n";
}

/**
 * Manual reference for project-level TOOLS + MCP servers. Plugins are NOT
 * duplicated here — they live in the runnable scripts/install-plugins.sh
 * (renderPluginsInstallScript). Everything below is commented: it includes
 * machine-level installs (rtk via brew, graphify via uv) that must be chosen,
 * so nothing auto-runs.
 * @param {string[]} mcpNames
 * @param {import('../data/tools-catalog.mjs').ToolDef[]} [tools]
 * @returns {string}
 */
export function renderInstallScript(mcpNames, tools = []) {
  const mcpComment = mcpNames.length > 0 ? mcpNames.map((n) => `#   - ${n}`).join("\n") : "#   (none recommended)";
  const toolLines = renderToolsInstallSection(tools);

  return `#!/usr/bin/env bash
# Generated by aia-harness — reference for project TOOLS + MCP servers.
# Review every line before running. Nothing here runs automatically.
# Plugins are installed separately — run scripts/install-plugins.sh (it is runnable),
# or let /aia-harness:init offer them interactively.
set -euo pipefail

# --- Project-level tools ----------------------------------------------------
${toolLines}

# --- MCP servers ------------------------------------------------------------
# The following strategic MCP servers were written to .mcp.json:
${mcpComment}
#
# Fill required secrets in .claude/settings.local.json (gitignored), then
# restart Claude Code so MCP servers load.

echo "Reference only. Plugins: run scripts/install-plugins.sh. Tools: uncomment a command above and re-run."
`;
}
