/**
 * Miscellaneous generated artifacts: strategy doc, .lsp.json, worktree config,
 * and the market install script.
 *
 * @module generate/misc
 */
import { commandsBlock } from "./claude-md.mjs";
import { marketplaceRepo } from "../data/plugins-catalog.mjs";

/** @typedef {import('../profile.mjs').ProjectProfile} ProjectProfile */

/** Map a primary language to a Language Server config. */
const LSP_SERVERS = {
  TypeScript: { command: "npx", args: ["-y", "typescript-language-server", "--stdio"] },
  JavaScript: { command: "npx", args: ["-y", "typescript-language-server", "--stdio"] },
  PHP: { command: "npx", args: ["-y", "intelephense", "--stdio"] },
  Python: { command: "npx", args: ["-y", "pyright-langserver", "--stdio"] },
  Go: { command: "gopls", args: [] },
  Rust: { command: "rust-analyzer", args: [] },
};

/**
 * @param {ProjectProfile} profile
 * @returns {string}
 */
export function renderStrategies(profile) {
  const c = profile.commands;
  const lang = profile.primaryLanguage ?? "unknown";
  return `# Harness strategies

Generated by aia-harness for a **${lang}** project (commands source: ${c.source}).

## Lint & format
${[c.lint && `- Lint: \`${c.lint}\``, c.format && `- Format: \`${c.format}\``].filter(Boolean).join("\n") || "- No linter detected. Consider adding one."}

## Compilation / typecheck
${c.typecheck ? `- \`${c.typecheck}\`` : "- No typecheck step detected."}

## Language server
${
  LSP_SERVERS[/** @type {keyof typeof LSP_SERVERS} */ (lang)]
    ? `- Suggested LSP: \`${LSP_SERVERS[/** @type {keyof typeof LSP_SERVERS} */ (lang)].command} ${LSP_SERVERS[/** @type {keyof typeof LSP_SERVERS} */ (lang)].args.join(" ")}\` (see \`.lsp.json\`).`
    : "- No standard language server mapping for this stack."
}

## Unit testing
${c.test ? `- \`${c.test}\`` : "- No test runner detected. Add one and wire it into CI."}

## Canonical command reference
${commandsBlock(c)}
`;
}

/**
 * @param {ProjectProfile} profile
 * @returns {string|null}
 */
export function renderLspJson(profile) {
  const lang = /** @type {keyof typeof LSP_SERVERS} */ (profile.primaryLanguage ?? "");
  const server = LSP_SERVERS[lang];
  if (!server) return null;
  const key = lang === "JavaScript" || lang === "TypeScript" ? "typescript" : lang.toLowerCase();
  return JSON.stringify({ lspServers: { [key]: { type: "stdio", ...server } } }, null, 2) + "\n";
}

/**
 * @returns {string}
 */
export function renderWorktreeInclude() {
  return `# Files copied into every new worktree (aia-harness)
.claude/settings.local.json
.env
.env.local
`;
}

/**
 * A runnable cross-platform installer for the suggested plugins.
 * Idempotent; prompts unless run with `-y`.
 * Generates a .mjs Node.js script (not bash).
 * @param {import('../data/plugins-catalog.mjs').PluginSuggestion[]} plugins
 * @returns {string}
 */
export function renderPluginsInstallScript(plugins) {
  const names = [...new Set(plugins.map((p) => p.marketplace))];
  const mpList = JSON.stringify(
    names.map((n) => [n, marketplaceRepo(n)]),
    null,
    2,
  );
  const pluginList = JSON.stringify(
    plugins.map((p) => ({ name: p.name, marketplace: p.marketplace })),
    null,
    2,
  );
  const listing = plugins.map((p) => `  - ${p.name} [${p.purpose}] ${p.description}`).join("\n");

  return `#!/usr/bin/env node
// Generated by aia-harness — install the suggested Claude Code plugins.
// Plugins install at USER level (Claude Code has no per-project plugin install).
// Run with -y to skip the confirmation prompt.
import { spawnSync } from "node:child_process";
import * as rl from "node:readline/promises";

const check = spawnSync("claude", ["--version"], { stdio: "ignore" });
if (check.status !== 0) {
  process.stderr.write("aia-harness: 'claude' CLI not found — install Claude Code first.\\n");
  process.exit(1);
}

const marketplaces = ${mpList};
const plugins = ${pluginList};

if (!process.argv.includes("-y")) {
  const iface = rl.createInterface({ input: process.stdin, output: process.stdout });
  const ans = await iface.question(
    \`About to add \${marketplaces.length} marketplace(s) and install \${plugins.length} plugin(s):\n${listing}\nProceed? [y/N] \`
  );
  iface.close();
  if (!ans.match(/^y$/i)) { console.log("Aborted."); process.exit(0); }
}

for (const [, repo] of marketplaces) {
  spawnSync("claude", ["plugin", "marketplace", "add", repo], { stdio: "inherit" });
}
for (const p of plugins) {
  spawnSync("claude", ["plugin", "install", p.name + "@" + p.marketplace], { stdio: "inherit" });
}
console.log("Done. Restart Claude Code to load the new plugins.");
`;
}

const GRAPHIFY_MEDIA_BLOCK = `# graphify extraction filters
# Skip binary/media files from semantic extraction
# (AST still processes code files normally)

# Images — rendered separately, not needed for semantic
*.png
*.jpg
*.jpeg
*.gif
*.svg
*.webp
*.ico

# PDFs — low signal-to-noise in semantic extraction
*.pdf

# Videos/audio — transcribed but usually verbose; filter at source if needed
*.mp4
*.mov
*.mp3
*.wav
*.flac

.claude/
docs/
.agents/
.code-review-graph/
.superpowers/

*.md`;

/**
 * @param {ProjectProfile} profile
 * @param {string[]} [gitignoreLines]  Lines from the project .gitignore (empty if none).
 * @returns {string}
 */
export function renderGraphifyignore(profile, gitignoreLines = []) {
  /** @type {string[]} */
  const sections = [
    "# .graphifyignore — gitignore syntax; seeded from project .gitignore + graphify extraction filters.",
  ];

  if (gitignoreLines.length > 0) {
    sections.push(...gitignoreLines, "");
  }

  const stackBase = [
    "node_modules/",
    "dist/",
    "build/",
    "out/",
    "coverage/",
    ".next/",
    ".nuxt/",
    ".turbo/",
    "*.min.js",
    "*.generated.*",
  ];
  /** @type {string[]} */
  const stackExtra = [];
  switch (profile.primaryLanguage) {
    case "Rust":
      stackExtra.push("target/");
      break;
    case "Java":
    case "Kotlin":
      stackExtra.push("target/", ".gradle/");
      break;
    case "PHP":
      stackExtra.push("vendor/");
      break;
    case "Go":
      stackExtra.push("vendor/", "bin/");
      break;
    case "Python":
      stackExtra.push("__pycache__/", ".venv/", "venv/", ".mypy_cache/");
      break;
    default:
      break;
  }
  sections.push(...stackBase, ...stackExtra, "", GRAPHIFY_MEDIA_BLOCK);

  return sections.join("\n") + "\n";
}
